#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

outerloop=1
innerloop=1
while [ "$outerloop" -lt 13 ]
do
	innerloop=1
	while [ "$innerloop" -lt 60 ]
	do
		echo "$innerloop";
		(( innerloop++ ))
	done
	echo "Hour: $outerloop"
	(( outerloop++ ))

done
